Create AV's Google Drive access.md
assemblee-virtuelle/Documentation pull request #7
Opened 2020-08-06 09:21 UTC by ValentineMathieu

2020-08-10 10:49 UTC, GuillaumeAV approved these changes

2020-08-10 14:28 UTC, MargauxSchulz requested changes
"For more transparency in the management of projects and in the life of the different communities, the Virtual Assembly makes sure to.."

2020-08-10 14:28 UTC, MargauxSchulz commented on AV's Google Drive access.md
> +For more transparency in the management of projects or the life of communities, the Virtual Assembly make sure to share with its most devoted contributors all the documents related to its activities.
"For more transparency in the management of projects and in the life of the different communities, the Virtual Assembly makes sure to.."

2020-08-11 08:58 UTC, MargauxSchulz approved these changes

2020-08-11 13:07 UTC, merged