Create Github's tutorial.md
assemblee-virtuelle/Documentation pull request #8
Opened 2020-08-06 09:51 UTC by ValentineMathieu

2020-08-10 10:48 UTC, GuillaumeAV approved these changes

2020-08-10 14:30 UTC, MargauxSchulz requested changes

2020-08-10 14:30 UTC, MargauxSchulz commented on Github's tutorial.md
> +In order to follow as closely as possible the progress of the Virtual Assembly's projects and to participate in the life of our community, what better way than to familiarize yourself with the tools
"In order to follow the progress of the VA's projects as closely as possible and to participate in the life of our community, what better way than to become familiar with the tools provided for this purpose ?!

2020-08-10 14:30 UTC, MargauxSchulz commented on Github's tutorial.md
> +Here is a tutorial that will allow you to enter the adventure without too many difficulties
"Here is a tutorial that will allow you to dive into this adventure without too many difficulties."

2020-08-10 14:30 UTC, MargauxSchulz commented on Github's tutorial.md
> +3. Make sure to be invited by the active contributor with whom you are in contact, by giving him/her with your email address or username
"by giving him/her your email address or username."

2020-08-10 14:30 UTC, MargauxSchulz commented on Github's tutorial.md
> +Avant de cliquer sur "commit changes" afin d'ajouter votre nouveau fichier ou de modifier un fichier déjà existant, assurez-vous de cocher la deuxième option (voir image ci-dessous). Cette dernière v
Au cas où c'est un oubli de trad, je te propose la suivante : 

Before clicking on "commit changes" in order to upload your new file or to modify an already existing file, make sure to check the second option (see picture below). This option will allow you to suggest a merging of your contribution to the project's "common core". Doing this will consequently put your file in the "**Pull request**" section. The contributors you chose to assign (cf "Issues" section below) will then be able to add their modifications, leave comments and decide whether or not to add your file to the project.

2020-08-10 14:40 UTC, ValentineMathieu commented on Github's tutorial.md
> +Avant de cliquer sur "commit changes" afin d'ajouter votre nouveau fichier ou de modifier un fichier déjà existant, assurez-vous de cocher la deuxième option (voir image ci-dessous). Cette dernière v
oh la la gros oubli merci !

2020-08-11 08:58 UTC, MargauxSchulz approved these changes

2020-08-11 13:07 UTC, merged